### ISSUE TITLE
Section Persistence events listeners uses static variables and this is misleading

### ISSUE THREAD

**Issue by galou** [mnesarco/fcapi#3]
In Section [Persistence events listeners](https://github.com/mnesarco/fcapi/blob/main/docs/documentation.md#persistence-events-listeners) the documentation may lead the workbench developer to understand that classes with the `@proxy` decorator are dataclasses. However, the variables `var1` and `var2` are static and this is for sure not what the developer wants.

**Comment by mnesarco** [comment]
Why do you think that var1 and var2 are static? They are not.

```python
class A:
  var1: int
  def __init__(self, v: int):
     self.var1 = v   # Sets a non static var in self instance
     A.var1 = 0      # Sets a static var in A class
```

Check

```
>>> a = A(1)
>>> b = A(2)
>>> 
>>> a.var1
1
>>> b.var1
2
>>> A.var1
0
>>> 

```

**Comment by galou** [comment]
Sorry, my mistake. I overlooked that `var1` and `var2` at the class level are just type hints and not an assignment. By the way since `A.var1` and `self.var1` are different variables, isn't the type hint documenting a different variable when used at the class level?

**Comment by mnesarco** [comment]
> By the way since `A.var1` and `self.var1` are different variables, isn't the type hint documenting a different variable when used at the class level?

Well, python type hints are not strong declarations as in other languages. They are there just to aid the linter, autocomplete and static analysis.
