### ISSUE TITLE
Extending from `GroupExtensionPython`

### ISSUE THREAD

**Issue by galou** [mnesarco/fcapi#5]
Here is a minimal piece of code I was expecting to work and behave as a group.
```python
from .fpo import proxy
from .fpo import view_proxy


@view_proxy(
    extensions=['Gui::ViewProviderGroupExtensionPython'],
)
class MyObjectViewProxy:
    pass


@proxy(
    object_type='App::FeaturePython',
    extensions=['App::GroupExtensionPython'],
    view_proxy=MyObjectViewProxy,
)
class MyObjectProxy:
    pass
```

The proxy works but the view proxy not. For example, I cannot toggle the visibility, the objects that belong to `Group` are not visible in the 3D view and the object doesn't "swallow" its children in the tree.

The view provider of my [Link](https://github.com/galou/freecad.cross/blob/main/freecad/cross/link_proxy.py) object works without issues but doesn't use fcapi.

What am I missing?

**Comment by mnesarco** [comment]
Hello @galou , thank you for the report. It is fixed now.

**Comment by mnesarco** [comment]
The python bindings for extensions are highly undocumented and maybe not completely implemented in FreeCAD, The `ViewProviderGroupExtensionPython` may work with some issues. But there is a different approach that works very well, it is deriving from `App::DocumentObjectGroupPython` instead of `App::FeaturePython`

```python

from fpo import proxy, view_proxy

# Optional
@view_proxy(icon='self:group.svg')
class MyGroupViewProxy:
    pass


# Proxy with GroupBehavior
@proxy(
    object_type='App::DocumentObjectGroupPython', # <----- Look here
    view_proxy=MyGroupViewProxy,
)
class MyGroupProxy:
    pass

# Use by just calling the create method from a macro or directly from the python
# console
def create_group():
    return MyGroupProxy.create(name="MyDocGroup")
    
```

With this approach everything works as expected

**Comment by galou** [comment]
Thanks @mnesarco, that was very quick!

I derived my object from `App::DocumentObjectGroupPython` in a first attempt but switched back to deriving from `App::FeaturePython` and using the appropriate extension. From my commit history, I wrote the comment:
```
The elements of the group are not placed inside the group on document restore (maybe a FreeCAD bug?).
```

Not 100% sure that the issue was not on my side though.

**Comment by mnesarco** [comment]
Ok, with `Gui::ViewProviderGroupExtensionPython` you have to manage the children visibility yourself as in your code in the on_change event handler.

**Comment by galou** [comment]
It's even more interesting. Making the object visible with the spacebar works but making it invisible not.

The visibility icon never changes, it remains as "invisible".
